# Generated by Django 6.0.4 on 2026-04-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.branch'),
        ),
    ]
