# Generated by Django 6.0.6 on 2026-06-05 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('schedule', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='schedule_le_date_050c82_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'date'], name='schedule_le_teacher_6c9a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date', 'start_time'], name='schedule_le_date_6ddde2_idx'),
        ),
    ]
