# Generated by Django 6.0.6 on 2026-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_lesson_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
